### ISSUE TITLE
Not compatible with .NET SDK version 6.0.101

### ISSUE THREAD

**Issue by Bhavik123-practice** [StefH/CoverageConverter#2]
I was able to execute this tool for .NET version 3.1.404 but we are trying to upgrade to .NET version 6.0.101 and the tool execution is failing with below error

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (x64) was not found.

**Comment by StefH** [comment]
I can make multiple versions.

Like 
3.1
5.0
and
6.0

Would that solve your issue?

**Comment by actionthomas** [comment]
As .net 6.0 is LTS, could you make this version ?

**Comment by StefH** [comment]
Would you suggest that I create a new version which only targets 6?

**Comment by StefH** [comment]
@Bhavik123-practice / @actionthomas 

Can you please test preview version `0.0.6-preview-01`?

**Comment by StefH** [comment]
@Bhavik123-practice / @actionthomas

Did you have time yet to test preview version 0.0.6-preview-01?

**Comment by iggymiggy** [comment]
@StefH I have tested version 0.0.6-preview-01 and can confirm that it is working properly

**Comment by StefH** [comment]
A new version will be released shortly.
